# Uncomment the next line to define a global platform for your project
project '../prj/BreakTime.xcodeproj'
platform :ios, '12.0'

target 'BreakTime' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for TodoListApp
  pod 'Alamofire'
  pod 'SVProgressHUD'
  pod 'SwiftyJSON'
  pod 'YoutubeDirectLinkExtractor'

end
